#!/bin/bash 
#BSUB -J data_preprocessing
#BSUB -q hpc                # Use CPU queue (as GPUs are not needed at all, since it is only for loading and plotting). 
#BSUB -W 1:00               # 1 hour           
#BSUB -n 1                  # 1 Core
#BSUB -R "rusage[mem=64GB]" # Request 64GB RAM to handle the big tensors with the expression data. 
#BSUB -R "span[hosts=1]"
#BSUB -o logs/data_preprocessing_%J.out # '%J' gives the jobID. 
#BSUB -e logs/data_preprocessing_%J.err
#BSUB -env "all"
#BSUB -B
#BSUB -N

# (optional) email
#BSUB -u s215065@dtu.dk    # <-- your email
#BSUB -B
#BSUB -N

#Making the logs folder in the root dir (DeepIsoQ/) if it doesn't exist already: 
mkdir -p logs

echo "Starting job on host: $(hostname)"
echo "Using Python from: $(which python)"
echo "Job started at: $(date)"

# Activate environment
source ~/.bashrc
source ../.venv/bin/activate #<--- Update venv name or use module load python/...

# Run the script
python data_preprocessing.py

echo "Job finished at: $(date)"

#Run the job using (cd to DeepIsoQ): 
# bsub < data_preprocessing.lsf
