#!/bin/bash
#BSUB -J bulkformer_cpu_more_mem
#BSUB -cwd /zhome/02/d/213485/DeepIsoQ/Bulkformer
#BSUB -o bulkformer_cpu.%J.out
#BSUB -e bulkformer_cpu.%J.err
#BSUB -q hpc
#BSUB -n 4
#BSUB -R "span[hosts=1]"
#BSUB -R "rusage[mem=48000]"
#BSUB -W 72:00

echo "=== CPU job started on $(date) ==="
echo "Host: $(hostname)"

module purge

source ~/deep_learning/bin/activate  

export PYTHONPATH="$BLACKHOLE/$USER/BulkFormer:$PYTHONPATH"

# CPU only (no GPU)
export CUDA_VISIBLE_DEVICES=""
echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"

# Run your transformer script that uses BulkFormer
python3 ~/DeepIsoQ/Bulkformer/extract_embedding_cpu.py

echo "=== CPU job finished on $(date) ==="
