#!/bin/bash
#BSUB -J ffnn_gpu
#BSUB -q gpuv100
#BSUB -gpu "num=1:mode=exclusive_process"
#BSUB -W 24:00
#BSUB -n 4
#BSUB -R "rusage[mem=32000] span[hosts=1]"
#BSUB -cwd .
#BSUB -o ffnn_search/logs/ffnn_%J.out
#BSUB -env "all"

# (optional) email
#BSUB -u s215065@dtu.dk     # <-- your email
#BSUB -B
#BSUB -N

# Safety: check GPU
if ! command -v nvidia-smi &> /dev/null; then
    echo "[ERROR] GPU not found. Exiting."
    exit 1
fi

echo "[INFO] GPU detected:"
nvidia-smi

module load cuda/12.8.1         # <-- your cuda version  (hint: you can also run 'module avail cuda')
source ../.venv/bin/activate          # <-- your environment path

echo "=== Starting training ==="
python3 ffnn_search/ffnn_arch_search_gpu.py            
